### ISSUE TITLE
如何制作数据集。

### ISSUE THREAD

**Issue by Kouuh** [shjwudp/shu#3]
你好，我想请教下，你仓库里提到的文本，原来是pdf格式吗？是的话，是怎样把它转存到txt文件中的？

**Comment by shjwudp** [comment]
@Kouuh 你好，欢迎提问，我手动收集了仓库里的书籍，但只有少部分原文件是pdf格式。现在在线的pdf转换工具已经很好用了，使用在线工具加少量的校对就可以整理出一本书籍。

**Comment by shjwudp** [comment]
因为不活跃关闭了。
